### ISSUE TITLE
IntelliJ's sources are not attached

### ISSUE THREAD

**Issue by ekudel** [JetBrains/intellij-platform-gradle-plugin#1504]
### What happened?

After switching to IDEA 2023.3, the platform's sources are not available, and ".class" files are opened instead. I also tried to create an empty plugin through "New Project" wizard and faced the same issue.

Note, that the issue occurs when I WORK in IDEA 2023.3 (Ultimate). It doesn't matter what "intellij.version" is set in "build.gradle".

### Steps to reproduce

1. Open IntelliJ IDEA 2023.3 Ultimate
2. Create a simple plugin through "New Project" wizard
3. Wait until configuring/indexing is finished
4. Try to open some platform's class (for example ApplicationManager)

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.4

### Operating System

macOS

**Comment by Undin** [comment]
@ekudel I suppose you need to enable `Download sources` option in `Advanced Settings`
See https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#attaching-sources

**Comment by ekudel** [comment]
@Undin Indeed, thank you! Really unobvious actually. IMO it should get offered here ("Download" link didn't work too):
<img width="612" alt="image" src="https://github.com/JetBrains/gradle-intellij-plugin/assets/6772218/cfee83df-a760-4252-afa5-04b6450655d7">

**Comment by Undin** [comment]
> IMO it should be offered here at least ("Download" link didn't work too btw)

@hsz Do I understand correctly that it will be implemented as a combination of gradle intellij plugin 2.0 + the corresponding changes in DevKit plugin?

**Comment by hsz** [comment]
Indeed, enabling the source download is necessary since `2022.2` and `2022.3` now, as @Undin mentioned above.

I'm aware of this inconvenience and will try to address that with DevKit enhancement and/or IntelliJ Platform Gradle Plugin 2.0.

**Comment by hsz** [comment]
Here is a quick summary of what was recently done in plugin development tooling regarding downloading IntelliJ Platform sources:

**Gradle IntelliJ Plugin 1.x**
The `intellij.downloadSources` property, responsible for downloading `IC` sources in the task configuration phase, is now applied to the `idea.module.downloadSources`, starting with `1.17.2` release.
`intellij.downloadSources` (by default true for non-CI environments) downloads `IC` sources for, i.e., `IU` or `PS`, as they don’t publish their sources to the Maven repository.

The _sources_ entry is added to the Ivy XML file.
With the above change, IDE respects that entry and attaches ideaIC-sources.jar to the IntelliJ Platform dependency.

**IntelliJ Platform Gradle Plugin 2.0**
We no longer download sources through the plugin, so there’s no intellij.downloadSources property.
However, the idea.module.downloadSources property is always set to true. Still, it is possible to opt-out from that using:
```
org.jetbrains.intellij.platform.buildFeature.downloadSources=false
```
Build Feature docs: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-gradle-properties.html#downloadSources

Still, the Gradle plugin doesn’t download sources! This operation is delegated to the DevKit plugin.

**DevKit 2024.1**
When using the IntelliJ Platform Gradle Plugin 2.x, DevKit will detect your IntelliJ Platform dependency.
If you use the `IC` or `PC`, sources will automatically be attached to the project thanks to the `idea.module.downloadSources` property described above.
For other non-`IC` dependencies, extra work is required, which is handled with a new AttachSourcesProvider implementation: DevKit will compose the `IC` (or `PC`) dependency coordinates using matching versions and download it in the same way IDE attaches sources for regular dependencies.
This won’t happen automatically (I was not able to automate it. Yet.), so the well-known action will be provided for you (see the screenshot) when you browse a compiled IntelliJ Platform dependency class.

![image](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/108333/4a75b753-1f7c-4571-bae5-d1c44b893e35)

**Comment by chylek-qr** [comment]
Is there any alternative way to download sources? This is the whole build.gradle.kts
```kotlin
plugins {
    id("java")
    id("org.jetbrains.intellij.platform") version "2.13.1"
    id("org.jetbrains.kotlin.jvm") version "2.2.20"
}

group = "quant"
version = "1.2"

repositories {
    mavenCentral()
    
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdea("2025.3.4")
        
        bundledPlugins("com.intellij.java")
    }
}

intellijPlatform {
    buildSearchableOptions.set(false)
    
    pluginConfiguration {
        ideaVersion {
            sinceBuild.set("253")
            untilBuild.set(provider { null })
        }
    }
}

kotlin {
    jvmToolchain(21)
}
```
I see the button to download:

<img width="1209" height="186" alt="Image" src="https://github.com/user-attachments/assets/d151030b-945b-4f63-8b97-f635d64535bb" />

but it doesn't do anything! It flashes a little "Downloading IntelliJ Platform sources..." in the notification bar for a second, and then nothing happens! The dedicated button doesn't work, the "Download Sources" button in the Gradle tool window doesn't work, and this is far from the first time this absolutely basic feature hasn't worked for me. It makes developing plugins for IJ so frustrating...

EDIT: I changed the version to `intellijIdea("2025.3.3")`, and now it works. I don't get it. Frustrating!

EDIT2: It half-worked. I opened another IJ class and it asked me to download sources again... but maybe it actually worked now?

Like, can we just do this through Gradle please? Have it work with this option, which I enabled because I **never ever** want to see decompiled sources.

<img width="508" height="101" alt="Image" src="https://github.com/user-attachments/assets/31e514b7-d22e-4723-9e24-9e4514a79cfc" />

I'm pretty sure all of this worked more reliably back in like 2021, especially before IntelliJ stopped downloading sources by default. It's just been getting worse since.
