### ISSUE TITLE
2.0 - Kotlin Functions with default values are not callable from Groovy

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/intellij-platform-gradle-plugin#1591]
### What happened?

```groovy
plugins {
  id("org.jetbrains.intellij.platform") version "2.0.0-beta1"
}

dependencies {
  intellijPlatform.pluginVerifier() // Workaround: Add "latest" as parameter
}
```

### Relevant log output or stack trace

```shell
Caused by: org.codehaus.groovy.runtime.metaclass.MethodSelectionException: Could not find which method pluginVerifier() to invoke from this list:
  public final void org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesExtension#pluginVerifier(java.lang.String)
  public final void org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesExtension#pluginVerifier(org.gradle.api.provider.Provider)
```

### Steps to reproduce

-

### Gradle IntelliJ Plugin version

2.0.0-beta1

### Gradle version

8.7

### Operating System

macOS

**Comment by hsz** [comment]
Fixed by involving `@JvmOverloads` along with helper functions for working with nested extensions: https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/d1bba44eed45ffdf0e51be8415e542fbe794abe8

The fix along with initial Groovy support is now available in `2.0.0-SNAPSHOT` release.
To use the snapshot releases, please follow: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#snapshot-release
