### ISSUE TITLE
Warn when using `plugin` instead of `bundledPlugin`

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/intellij-platform-gradle-plugin#1808]
### Describe the need of your request

If project refers to `plugin("ID")` while the plugin with such id is indeed _bundled_ in the target IDE, fail the build and require to use correct `bundledPlugin("ID")` instead.

Another hint could be missing specification of plugin version in passed ID. 

This could become more and more prominent source of error/confusion with unbundlling and publishing bundled plugins on MP.

### Proposed solution

see above

**Comment by AlexanderBartash** [comment]
That is a different thing. It creates a dynamic "catalog", i.e. on practice you reference libs (in our case plugins) not by hard-coding their coordinates as a string, but instead use a type-safe accessor like `bundledPlugins.Tomcat` if after the IDE upgrade the tomcat is gone it would probably show an error in the editor since Tomcat is not present anymore, but it will require project refresh most likely.

**Comment by YannCebron** [comment]
Not sure how this would work when targeting different IDEs/versions or switching in one project... The current mechanism of using plugin IDs seems sufficient  IMHO.

**Comment by YannCebron** [comment]
see #1810

**Comment by hsz** [comment]
Implemented with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/212af387d5d4278fd550ed7975141b02b78a9d7e
