### ISSUE TITLE
No support for Gradle `dependencyResolutionManagement`

### ISSUE THREAD

**Issue by turansky** [JetBrains/intellij-platform-gradle-plugin#776]
Repositories in `dependencyResolutionManagement` = failed build

[Build](https://github.com/turansky/yfiles-kotlin/actions/runs/1172675407)
[Change](https://github.com/turansky/yfiles-kotlin/commit/b6c700cc1fbb4807749ecaac8c58615236af0f00) - `idea-plugin` folder

**Comment by hfhbd** [comment]
Similar to https://github.com/JetBrains/gradle-grammar-kit-plugin/pull/107 I would just add a check and don't add custom repositories. Adding repositories inside a plugin isn't secure because you can't control it and this repository can contain additional dependencies replacing your dependencies with bad ones.

**Comment by rock3r** [comment]
Looking forward to get this addressed for Jewel, too :)

**Comment by hsz** [comment]
Looks like we need to rework dependencies management to something less magical.

**Comment by hsz** [comment]
Implemented in 2.0.
It is possible to apply the `org.jetbrains.intellij.platform.settings` plugin in `settings.gradle.kts`, which also provides a set for repository helpers to let you add all necessary repositories to the project.

See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#configuration.dependencyResolutionManagement
